name: bus_driver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.8
  provider: ^6.0.2
  flutter_translate: ^3.0.1
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  package_info_plus: ^1.3.0
  connectivity_plus: ^2.0.2
  google_maps_flutter: ^2.1.0
  geolocator: ^8.1.1
  maps_toolkit: ^2.0.0
  flutter_animarker: ^3.2.0
  intl: ^0.17.0
  device_info_plus: ^3.1.1
  flutter_svg: ^1.0.3
  flutter_login: ^3.1.0
  flutter_secure_storage: ^5.0.2
  audioplayers: ^0.20.1
  background_location: ^0.8.1
  ntp: ^2.0.0
  rive: ^0.8.1
  flutter_native_splash: ^2.0.2
  day_picker: ^2.1.0
  time_range: ^1.0.2
  flutter_cube: ^0.1.1
  rate_limiter: ^0.1.1

  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#0E8B8B"
  adaptive_icon_foreground: "assets/images/ic_launcher_front.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: "#fffcfc"
  color_dark: "#383434"
  image: assets/images/ic_launcher_splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/i18n/
    - assets/images/
    - assets/maps/
    - assets/rive/
    - assets/
